### ISSUE TITLE
Breaks Bidrectional clipboard and copy

### ISSUE THREAD

**Issue by AirHeadsbuirse** [d4rksystem/VBoxCloak#1]
Looks like modifying the system files is a bad idea and theres no way of reverting the changes once done. 

Im using a Windows 10 VM w Vbox 7.1

**Comment by d4rksystem** [comment]
Hi! Thanks for reporting this! 

This is not really an issue, for 2 reasons:

1. The way this script is designed, it does indeed break VirtualBox functionalities like copy/paste. I have this warning in the Readme file :)
2. There is a way to revert changes - Just take a snapshot of the VM and revert.

If I misunderstood the issue, please let me know! Hope this clears things up.

**Comment by AirHeadsbuirse** [comment]
Ah touche! I completely misread that in the README, any idea what change in particular breaks the copy/paste function? I'm going to reinstall a new box and try again! Solid work btw
