### ISSUE TITLE
Does this work for non Virtualbox VM like the one from VMware or Virt Manager

### ISSUE THREAD

**Issue by dhupee** [d4rksystem/VBoxCloak#2]
Hi I like your software, it works when Im using Virtualbox, but recently I switch to Virt-manager

and I'm wondering whether there are fellow users who use this in other VM software find this worked as well??

thank you

**Comment by d4rksystem** [comment]
Thank you!! Virtu-manager (KVM, Xen, and LXC) are not supported in my script as of this moment. I may decided to include these in the future, but as I do not use these platforms, I do not currently have a way to develop for them or test them. :(
