### ISSUE TITLE
Feature request: Support for VMware Workstation 17 Pro

### ISSUE THREAD

**Issue by Weingartens** [d4rksystem/VBoxCloak#3]
Thank you very much for the script. Support for VMware Workstation 17 Pro would be great. Unfortunately it doesn't work at the moment:

`PS C:\Users\Me\Desktop> .\"New Text Document.ps1" -all
VBoxCloak.ps1 by @d4rksystem (Kyle Cucci)
Usage: VBoxCloak.ps1 -<option>
Example Usage: VBoxCloak.ps1 -all
Options:
all: Enable all options.
reg: Make registry changes.
procs: Kill processes.
files: Make file system changes.
Tips: Run as Admin or you will get a lot of errors!
Warning: Only run in a virtual machine!
*****************************************
[*] Attempting to kill VMware processes...
[!] VBoxTray process does not exist!
[!] VBoxService process does not exist!
[!] VBoxControl process does not exist!
[+] Modifying Reg Key HKLM:\HARDWARE\Description\System\SystemBiosVersion...
[+] Modifying Reg Key Values in HKLM:\SYSTEM\CurrentControlSet\Control\SystemInformation...
[!] Reg Key HKLM:\HARDWARE\Description\System\SystemBiosDate does not seem to exist! Skipping this one...
[!] Reg Key HKLM:\HARDWARE\Description\System\VideoBiosVersion does not seem to exist! Skipping this one...
[!] Reg Key HKLM:\SOFTWARE\Oracle\VirtualBox Guest Additions does not seem to exist, or has already been renamed! Skipping this one...
[!] Reg Key HKLM:\HARDWARE\ACPI\DSDT\VBOX__ does not seem to exist, or has already been renamed! Skipping this one...
[!] Reg Key HKLM:\HARDWARE\ACPI\FADT\VBOX__ does not seem to exist, or has already been renamed! Skipping this one...
[!] Reg Key HKLM:\HARDWARE\ACPI\RSDT\VBOX__ does not seem to exist, or has already been renamed! Skipping this one...
[!] Reg Key HKLM:\SYSTEM\ControlSet001\services\VBoxMouse does not seem to exist, or has already been renamed! Skipping this one...
[!] Reg Key HKLM:\SYSTEM\ControlSet001\services\VBoxService does not seem to exist, or has already been renamed! Skipping this one...
[!] Reg Key HKLM:\SYSTEM\ControlSet001\services\VBoxSF does not seem to exist, or has already been renamed! Skipping this one...
[!] Reg Key HKLM:\SYSTEM\ControlSet001\services\VBoxVideo does not seem to exist, or has already been renamed! Skipping this one...
[!] Reg Key HKLM:\SYSTEM\ControlSet001\services\VBoxGuest does not seem to exist, or has already been renamed! Skipping this one...
[!] Reg Key HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run\VBoxTray does not seem to exist, or has already been renamed! Skipping this one...
[!] Reg Key HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Oracle VM VirtualBox Guest Additions does not seem to exist, or has already been renamed! Skipping this one...
[!] Reg Key HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Oracle VM VirtualBox Guest Additions does not seem to exist, or has already been renamed! Skipping this one...
[*] Attempting to rename VirtualBox driver files...
[+] Attempting to rename VBoxMouse.sys...
[!] File does not seem to exist! Skipping...
[+] Attempting to rename VBoxSF.sys...
[!] File does not seem to exist! Skipping...
[+] Attempting to rename VBoxWddm.sys...
[!] File does not seem to exist! Skipping...
[+] Attempting to rename VBoxGuest.sys...
[!] File does not seem to exist! Skipping...
[*] Attempting to rename System32 VirtualBox executable files...
[+] Attempting to rename VBoxTray.exe...
[!] File does not seem to exist! Skipping...
[+] Attempting to rename VBoxControl.exe...
[!] File does not seem to exist! Skipping...
[+] Attempting to rename VBoxService.exe...
[!] File does not seem to exist! Skipping...
[+] Attempting to rename VBoxMRXNP.dll...
[!] File does not seem to exist! Skipping...
[+] Attempting to rename VBoxSVGA.dll...
[!] File does not seem to exist! Skipping...
[+] Attempting to rename VBoxHook.dll...
[!] File does not seem to exist! Skipping...
[+] Attempting to rename VBoxNine.dll...
[!] File does not seem to exist! Skipping...
[+] Attempting to rename VBoxGL.dll...
[!] File does not seem to exist! Skipping...
[+] Attempting to rename VBoxDispD3D.dll...
[!] File does not seem to exist! Skipping...
[+] Attempting to rename VBoxICD.dll...
[!] File does not seem to exist! Skipping...
[*] Attempting to rename SysWOW64 VirtualBox executable files...
[+] Attempting to rename VBoxGL-x86.dll...
[!] File does not seem to exist! Skipping...
[+] Attempting to rename VBoxMRXNP.dll...
[!] File does not seem to exist! Skipping...
[+] Attempting to rename VBoxDispD3D-x86.dll...
[!] File does not seem to exist! Skipping...
[+] Attempting to rename VBoxICD-x86.dll...
[!] File does not seem to exist! Skipping...
[+] Attempting to rename VBoxSVGA-x86.dll...
[!] File does not seem to exist! Skipping...
[+] Attempting to rename VBoxNine-x86.dll...
[!] File does not seem to exist! Skipping...
[+] Attempting to rename VirtualBox program directory...
Get-ChildItem : Cannot find path 'C:\Program Files\Oracle' because it does not exist.
At C:\Users\Me\Desktop\New Text Document.ps1:342 char:13
+     $vboxDir = Get-ChildItem "C:\Program Files\Oracle\VirtualBox*"
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program Files\Oracle:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

[!] Directory does not appear to exist! Skipping...

** Done! Did you recieve a lot of errors? You need to run as Admin!
** Spot any bugs or issues? DM me on Twitter or open an issues on Github! :)
PS C:\Users\Me\Desktop>

`

**Comment by d4rksystem** [comment]
Hi! Sorry for the late response!

I see you are using VBoxCloak. This is specifically for **VirtualBox** VM's. You should be using **VMwareCloak** ;) Try this and let me know how it works!

https://github.com/d4rksystem/VMwareCloak
